version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/jdk11"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "docker"
    directory: "/jdk8"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
