name: Docker build

on: [push, pull_request]

jobs:
  jdk11:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build
      run: docker build --tag maven-alpine:jdk11 --file ./jdk11/Dockerfile ./jdk11/
      
  jdk16:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build
      run: docker build --tag maven-alpine:jdk16 --file ./jdk16/Dockerfile ./jdk16/
