name: Docker build

on: [push, pull_request]

jobs:
  jdk11:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker buildx build --tag ghcr.io/edumco/maven-alpine:jdk11 .
      
    - name: Login on Container Registry
      uses: docker/login-action@v1.14.1
      if: contains( ${{ github.head_ref }}, "main" )
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push image to register
      if: contains( ${{ github.head_ref }}, "main" )
      run: docker push ghcr.io/edumco/maven-alpine:jdk11
      
  jdk17:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker buildx build --tag ghcr.io/edumco/maven-alpine:jdk17 --build-arg JDK_IMAGE=openjdk:17-alpine .
      
    - name: Login on Container Registry
      uses: docker/login-action@v1.14.1
      if: contains( ${{ github.head_ref }}, "main" )
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push image to register
      if: contains( ${{ github.head_ref }}, "main" )
      run: docker push ghcr.io/edumco/maven-alpine:jdk17
      
