name: Docker build

on: [push, pull_request]

jobs:
  jdk11:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build
      run: DOCKER_BUILDKIT=1 docker build --tag ghcr.io/edumco/maven-alpine:jdk11 .
      
    - name: Login on Container Register
      if: contains( ${{ github.head_ref }}, "main" )
      run: echo $CR_PAT | docker login ghcr.io -u edumco --password-stdin
      env:
        CR_PAT: ${{ secrets.CONTAINER_REGISTRY }}
        
    - name: Push image to register
      if: contains( ${{ github.head_ref }}, "main" )
      run: docker push ghcr.io/edumco/maven-alpine:jdk11
      
  jdk16:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Build
      run: DOCKER_BUILDKIT=1 docker build --tag ghcr.io/edumco/maven-alpine:jdk16 --build-arg JDK_IMAGE=adoptopenjdk/openjdk16:alpine-slim .
      
    - name: Login on Container Register
      if: contains( ${{ github.head_ref }}, "main" )
      run: echo $CR_PAT | docker login ghcr.io -u edumco --password-stdin
      env:
        CR_PAT: ${{ secrets.CONTAINER_REGISTRY }}
        
    - name: Push image to register
      if: contains( ${{ github.head_ref }}, "main" )
      run: docker push ghcr.io/edumco/maven-alpine:jdk16
      
