name: Maven with JDK 11

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.5.0

    - name: Build
      run: cd /jdk11 && docker build . 
