name: Maven JDK 11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Build
      run: docker build --file ./jdk11/Dockerfile 
